version: '3'
services: 
  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin      
    
  plugin:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coverage:/usr/app/coverage
      - ./.nyc_output:/usr/app/.nyc_output
      - ./mochawesome-report:/usr/app/mochawesome-report
    depends_on:
      - keycloak
    