version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    command: start-dev

  plugin:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coverage:/usr/app/coverage
      - ./mochawesome-report:/usr/app/mochawesome-report
    depends_on:
      - keycloak
